### ISSUE TITLE
CPU Credit Balance complaining in serverless cluster on dev/test

### ISSUE THREAD

**Issue by sandromlp** [marbot-io/terraform-aws-marbot-monitoring-rds-cluster#1]
https://github.com/marbot-io/terraform-aws-marbot-monitoring-rds-cluster/blob/4bb03995d6aed025a5e6a2c2378473fe9e7b7f14/main.tf#L156

It would be good if we could turn this off separately with another bool, so `enabled && credit_check_enabled`  basically, which would enable silencing this on dev/test/stage environments where we may not care as much about it.
furthermore, this is less interesting if there is autoscaling enabled using aurora MySQL serverless as the cluster can always scale up :)

**Comment by michaelwittig** [comment]
Hi @sandromlp 

I agree that this check doesn't make much sense for Aurora Serverless. 

It makes sense to enable/disable the alarm to save costs as well (we pay for alarms). It is only important if workloads run on t2/t3 instances.

PR is coming soon..

**Comment by michaelwittig** [comment]
Version `0.3.0` of the `marbot-io/marbot-monitoring-rds-cluster/aws` module contains a `burst_monitoring_enabled ` variable that you can set to false.
